version: '3.8'

services:
  events-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./events:/root/events
    environment:
      - ENV=development
      - PORT=8080
    restart: unless-stopped
